[build]
  publish = "public"
  functions = "netlify/functions"
  command = "bash ./netlify/functions/setup.sh"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "16"
  NPM_VERSION = "8"
  PIPENV_RUNTIME = "3.9"
  PYTHON_RUNTIME = "3.9"
  PATH = "/opt/buildhome/.local/bin:/opt/buildhome/python/bin:$PATH"
  PIP_USER = "1"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/python/**"]

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/analyze"
  to = "/.netlify/functions/api"
  status = 200
  force = true
  query = { action = "analyze" }

[[redirects]]
  from = "/api/technical"
  to = "/.netlify/functions/api"
  status = 200
  force = true
  query = { action = "technical" }

[[redirects]]
  from = "/api/pattern"
  to = "/.netlify/functions/api"
  status = 200
  force = true
  query = { action = "pattern" }

[[redirects]]
  from = "/api/trend"
  to = "/.netlify/functions/api"
  status = 200
  force = true
  query = { action = "trend" }

[[redirects]]
  from = "/api/chart"
  to = "/.netlify/functions/api"
  status = 200
  force = true
  query = { action = "chart" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"