[build]
  publish = "public"
  functions = "netlify/functions"
  command = "bash netlify/functions/build.sh"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@types/node"]

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "16"
  PYTHONPATH = "/opt/build/repo/netlify/functions"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/analyze"
  to = "/.netlify/functions/smc_analyzer"
  status = 200
  force = true

[[redirects]]
  from = "/api/technical"
  to = "/.netlify/functions/technical_indicators"
  status = 200
  force = true

[[redirects]]
  from = "/api/pattern"
  to = "/.netlify/functions/pattern_recognition"
  status = 200
  force = true

[[redirects]]
  from = "/api/trend"
  to = "/.netlify/functions/trend_prediction"
  status = 200
  force = true

[[redirects]]
  from = "/api/chart"
  to = "/.netlify/functions/charts"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[context.production.environment]
  SUPABASE_URL = "https://vkiqitvhfyvqomvkmglz.supabase.co"
  SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZraXFpdHZoZnl2cW9tdmttZ2x6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDkxNzE2MTcsImV4cCI6MjAyNDc0NzYxN30.PomX5qS0oRd3kcPvkf6PMYJIAhy29mbgvzJ5XGjgcW8"
  DEBUG = "False"
  PORT = "8080"
  MODEL_TYPE = "rf"
